[package]
name = "hyper2"
version = "1.5.5"
description = "A protective and efficient HTTP library for all."
readme = "README.md"
documentation = "https://docs.rs/hyper2"
repository = "https://github.com/penumbra-x/hyper2"
license = "MIT"
authors = ["0x676e67 <gngppz@gmail.com>"]
keywords = ["http", "hyper2", "hyperium"]
categories = ["network-programming", "web-programming::http-client", "web-programming::http-server"]
edition = "2021"
rust-version = "1.63" # keep in sync with MSRV.md dev doc

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
]

[dependencies]
bytes = "1.2"
http = "1"
http-body = "1"
tokio = { version = "1", features = ["sync"] }

# Optional

futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false }
h2 = { version = "0.4.10", package = "http2", features = ["unstable"]}
http-body-util = "0.1"
httparse = "1.9"
itoa = "1"
pin-project-lite = "0.2.4"
smallvec = { version = "1.12", features = ["const_generics", "const_new"] }
tracing = { version = "0.1", default-features = false, features = ["std"], optional = true }
want = "0.3"

[dev-dependencies]
form_urlencoded = "1"
futures-channel = { version = "0.3", features = ["sink"] }
futures-util = { version = "0.3", default-features = false, features = ["alloc", "sink"] }
http-body-util = "0.1"
pretty_env_logger = "0.5"
pin-project-lite = "0.2.4"
spmc = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = [
    "fs",
    "macros",
    "net",
    "io-std",
    "io-util",
    "rt",
    "rt-multi-thread", # so examples can use #[tokio::main]
    "sync",
    "time",
    "test-util",
] }
tokio-test = "0.4"
tokio-util = "0.7.10"

[features]
# Nothing by default
default = []

# Utilize tracing (currently unstable)
tracing = ["dep:tracing"]

# Http2 tracing
http2-tracing = ["h2/tracing"]

# internal features used in CI
nightly = []

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(hyper_unstable_tracing)',
    'cfg(hyper_unstable_ffi)'
]

[package.metadata.docs.rs]
features = ["ffi", "full", "tracing"]
rustdoc-args = ["--cfg", "hyper_unstable_ffi", "--cfg", "hyper_unstable_tracing"]

[package.metadata.playground]
features = ["full"]

[package.metadata.capi.header]
generation = false
subdirectory = false

[package.metadata.capi.install.include]
asset = [{ from="capi/include/hyper2.h" }]

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false

[[example]]
name = "client"
path = "examples/client.rs"

[[example]]
name = "client_json"
path = "examples/client_json.rs"
